CREATE table "User"(
	user_id int primary key GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	username varchar(255) NOT NULL UNIQUE,
	password VARCHAR(60),
	refresh_token TEXT,
	profile_picture varchar(255),
	profile_description TEXT,
	favourite_movie int
);

CREATE table "Group"(
	group_id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	group_name varchar(255) NOT NULL UNIQUE,
	group_owner INT NOT NULL,
    FOREIGN KEY (group_owner) REFERENCES "User" (user_id),
	group_icon varchar(255),
	group_description TEXT,
	group_favourite_movie int
);

CREATE table User_Groups(
	user_id INT NOT NULL,
    group_id INT NOT NULL,
   	--Primary key sen takia, että user ei voi liittyä samaan ryhmään useamman kerran,
	--jos on jo jäsen
    PRIMARY KEY (user_id, group_id), 
    FOREIGN KEY (user_id) REFERENCES "User" (user_id)  ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES "Group" (group_id) ON DELETE CASCADE
);

CREATE table Favourites(
	favourite_id int PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES "User" (user_id) ON DELETE CASCADE, 
	movie_id int NOT NULL,
	poster_path varchar(255) NOT NULL,
	movie_name varchar(255) NOT NULL
);

CREATE table Reviews(
	review_id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	--int(0-5) ei ollut validi, tällä rajoitetaan tuo olemaan 0-5
	review_rating int NOT NULL CHECK (review_rating BETWEEN 0 AND 5),
	username varchar(255) NOT NULL,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES "User" (user_id) ON DELETE CASCADE,
	review_description varchar(255),
	review_date TIMESTAMP NOT NULL,
	movie_id int NOT NULL,
	poster_path varchar(255) NOT NULL,
	movie_name varchar(255) NOT NULL
);

CREATE table Group_Request(
	request_id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	user_id INT NOT NULL,
	group_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES "User" (user_id) ON DELETE CASCADE,
	FOREIGN KEY (group_id) REFERENCES "Group" (group_id) ON DELETE CASCADE,
	--Vakiona ei hyväksytty, säästytään nullin käsittelyltä
	request_accepted BOOLEAN DEFAULT FALSE
);

INSERT INTO "User" (username, password, refresh_token, profile_picture, profile_description, favourite_movie)
VALUES 
('testuser1', '$2b$10$KeIUNJGhjwu/KqWlT0kUX.o85DvJqzbtWEo2Cnd7g5rEQ2xEfC9ku', 'testing', 'profile_pic', 'This is test user 1.', 1),
('testuser2', 'testpwd2', 'testint2', 'profile_pic2', 'This is test user 2.', 2);

INSERT INTO Favourites (user_id, movie_id, poster_path, movie_name)
VALUES 
(1, 293660, '/3E53WEZJqP6aM84D8CckXx4pIHw.jpg', 'Deadpool');

INSERT INTO Reviews (user_id, username, review_rating, review_description, review_date, movie_id, poster_path, movie_name)
VALUES 
(1, 'testuser1', 4, 'Great movie!', NOW(), 293660, '/3E53WEZJqP6aM84D8CckXx4pIHw.jpg', 'Deadpool');

INSERT INTO "Group" (group_name, group_owner, group_icon, group_description, group_favourite_movie)
VALUES 
('Test Group 1', 1, 'group_icon1', 'This is test group 1.', 293660),
('Test Group 2', 2, 'group_icon2', 'This is test group 2.', 533535);